os: linux
dist: xenial
language: ruby

services:
- docker

env:
- OS=ubuntu18.04
- OS=ubuntu20.04
- OS=centos7
- OS=centos8

script:
- docker=$(git --no-pager diff --name-only $TRAVIS_COMMIT_RANGE | grep '^docker' ) ;
  [ -z ${docker} ] || docker build -t electronioncollider/spack-builder:$OS -f docker/$OS/Dockerfile docker
- docker=$(git --no-pager diff --name-only $TRAVIS_COMMIT_RANGE | grep '^docker' ) ;
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ;
  if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      [ -z ${docker} ] || docker push electronioncollider/spack-builder:$OS ;
    fi
  fi

jobs:
  include:
  - stage: check specs
    script:
    - packages=$(git --no-pager diff --name-only $TRAVIS_COMMIT_RANGE | sed -n 's|^packages/\(.*\)/package.py|\1|p' ) ;
      echo Changed packages are ${packages} ;
      [ -z ${packages} ] || for package in escalate ${packages} ; do
        if [ ! -f packages/${package}/package.py ] ; then continue ; fi ;
        docker run --rm -it electronioncollider/spack-builder:$OS /bin/bash -c " \
          versions=\`spack versions ${package}\` ;
          echo Versions for ${package} are ${versions} ; \
          for version in ${versions} ; do \
            spack spec -I ${package}@${version} ; \
          done \
        " ;
      done
