name: Build Environments

on: [push, pull_request]

jobs:
  generate-matrix:
    name: Generate matrix for build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          JSON="{\"include\":["
          for env in eic ; do
            for os in centos7 centos8 ubuntu20.04 ubuntu20.10 ; do 
              # Add build to the matrix only if it is not already included
              JSONline="{\"env\": \"$env\", \"os\": \"$os\"},"
              if [[ "$JSON" != *"$JSONline"* ]]; then
                JSON="$JSON$JSONline"
              fi              
            done
          done
          
          # Remove last "," and add closing brackets
          if [[ $JSON == *, ]]; then
            JSON="${JSON%?}"
          fi
          JSON="$JSON]}"
          echo $JSON
          
          # Set output
          echo "::set-output name=matrix::$( echo "$JSON" )"

  build:
    name: Build ${{ matrix.env }} on ${{ matrix.os }}
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cvmfs-contrib/github-action-cvmfs@v2
      - name: Build environment ${{ matrix.env }} on ${{ matrix.os }}
        run: |
          mkdir -p ~/.spack && echo -e "repos::\n  - $(pwd)\n  - \$spack/var/spack/repos/builtin" > ~/.spack/repos.yaml
          /cvmfs/oasis.opensciencegrid.org/mis/singularity/bin/singularity run -B /cvmfs:/cvmfs /cvmfs/eic.opensciencegrid.org/singularity/spack-builder:${{ matrix.os }} bash -c "spack debug report && spack repo list && spack env create --without-view -d environments/${{ matrix.env }} && spack env activate --without-view environments/${{ matrix.env }} && spack concretize && spack install"
