name: Check for new versions

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
  schedule:
    - cron: "0 13 * * 1" # Every Monday at 1PM UTC (9AM EST)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup spack
      run: |
        mkdir ${GITHUB_WORKSPACE}/../spack
        cd ${GITHUB_WORKSPACE}/../spack
        git clone --depth 1 --branch develop https://github.com/spack/spack .
        cp -r ${GITHUB_WORKSPACE} var/spack/repos/
        #cp var/spack/repos/$(basename ${GITHUB_REPOSITORY})/environments/eic/packages.yaml etc/spack
        source share/spack/setup-env.sh
        spack repo add --scope site ${PWD}/var/spack/repos/$(basename ${GITHUB_REPOSITORY})
    - name: Check for New Versions and Create Issue 
      env:
        EICSPACK_COMMENT_BOT_TOKEN: ${{ secrets.EICSPACK_COMMENT_BOT_TOKEN }}
      run: |
        cd ${GITHUB_WORKSPACE}/../spack
        source share/spack/setup-env.sh
        ${GITHUB_WORKSPACE}/.github/scripts/generate_new_version_issue.sh
        ${GITHUB_WORKSPACE}/.github/scripts/post_new_version_issue_comment.sh
        
